/** Синхронно с server/reactions.js — полный список реакций для UI. */
export const REACTION_CATALOG = [
  { kind: 'like', emoji: '👍' },
  { kind: 'heart', emoji: '❤️' },
  { kind: 'fire', emoji: '🔥' },
  { kind: 'clap', emoji: '👏' },
  { kind: '100', emoji: '💯' },
  { kind: 'joy', emoji: '😂' },
  { kind: 'cry', emoji: '😢' },
  { kind: 'think', emoji: '🤔' },
  { kind: 'eyes', emoji: '👀' },
  { kind: 'rocket', emoji: '🚀' },
  { kind: 'party', emoji: '🎉' },
  { kind: 'ok', emoji: '👌' },
  { kind: 'star', emoji: '⭐' },
  { kind: 'thumbs_down', emoji: '👎' },
  { kind: 'pray', emoji: '🙏' },
  { kind: 'muscle', emoji: '💪' },
  { kind: 'sparkles', emoji: '✨' },
  { kind: 'bulb', emoji: '💡' },
  { kind: 'handshake', emoji: '🤝' },
  { kind: 'wave', emoji: '👋' },
  { kind: 'raised_hands', emoji: '🙌' },
  { kind: 'melting', emoji: '🫠' },
  { kind: 'skull', emoji: '💀' },
  { kind: 'goat', emoji: '🐐' },
  { kind: 'chart', emoji: '📈' },
  { kind: 'target', emoji: '🎯' },
  { kind: 'coffee', emoji: '☕' },
  { kind: 'pizza', emoji: '🍕' },
  { kind: 'moon', emoji: '🌙' },
  { kind: 'sun', emoji: '☀️' },
  { kind: 'gift', emoji: '🎁' },
  { kind: 'warning', emoji: '⚠️' },
  { kind: 'question', emoji: '❓' },
]
